version: 2

# Build configuration for GoReleaser
builds:
  - id: pab
    main: ./cmd/pab/main.go
    binary: pab
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    # Set linker flags for version information
    ldflags:
      - -s -w -X main.Version={{.Version}} -X main.Commit={{.Commit}} -X main.Date={{.Date}}

# Archive configuration for standard binaries
archives:
  - id: pab-archive
    # Use standard archive names: e.g. pab_1.0.0_linux_amd64.tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE*

# nfpm configuration to build debian (.deb) packages
nfpms:
  - id: pab-nfpms
    package_name: pab
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    homepage: https://github.com/pharos-systems-llc/pharos-advanced-blocking
    maintainer: Pharos Advanced Blocking Team
    description: Advanced Blocking application.
    license: AGPL-3.0
    formats:
      - deb


# Sign the checksums file using Cosign (keyless signing using OIDC)
signs:
  - id: pab-signing
    artifacts: checksum
    cmd: cosign
    signature: "${artifact}.sigstore.json"
    args:
      - sign-blob
      - "--yes"
      - "--bundle=${signature}"
      - "${artifact}"


# Checksums generation configuration
checksum:
  name_template: "checksums.txt"

# Snapshot build config
snapshot:
  version_template: "{{ incpatch .Version }}-next"

# Changelog generation config
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
